### ISSUE TITLE
Deploy Times 1840-1920 models

### ISSUE THREAD

**Issue by jgonggrijp** [UUDigitalHumanitieslab/ShiCo#9]
Different set, different server from and in addition to #5. Depends on #8.

**Comment by jgonggrijp** [comment]
This has been an unexpected struggle, but it appears I got it to work. For future reference: if you run into a 500 internal server error, try

```console
$ sudo a2enmod proxy_http
$ sudo service apache2 restart
```

**Comment by BeritJanssen** [comment]
This can be closed, after adding some information to the website as requested by Jaap.
